resources:
  containers:
    - container: dotnetsdk
      image: microsoft/dotnet:2.1.503-sdk-stretch
    - container: dind
      image: docker:latest

jobs:
  - job: set_version
    pool: AWS Ubuntu
    container: dotnetsdk
    steps:
      - script: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet tool install -g nbgv
          nbgv cloud -a
      - bash: echo '##vso[task.setvariable variable=nbgv_nuget;isOutput=true]$(NBGV_NuGetPackageVersion)'
        name: set_variable
  - job: task_build
    dependsOn: set_version
    pool: AWS Ubuntu
    container: dotnetsdk
    steps:
      - task: DotNetCoreCLI@2
        displayName: Dotnet Build
        inputs:
          command: build
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: Dotnet Test
        inputs:
          command: test
          projects: '**/*Tests.csproj'
  - job: docker_build
    dependsOn: task_build
    pool: AWS Ubuntu
    variables:
      nbgv_nuget: $[ dependencies.set_version.outputs['set_variable.nbgv_nuget'] ]
    steps:
      - bash: echo $(nbgv_nuget)
      - bash: echo $NBGV_NUGET
      - task: Docker@1
        displayName: Docker Build
        inputs:
          command: build
          imageName: deployment:$(nbgv_nuget)
  - job: cake_build
    pool: AWS Ubuntu
    dependsOn: set_version
    container: dotnetsdk
    steps:
      - script: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet tool install -g Cake.Tool --version 0.32.0
          dotnet cake --bootstrap
          dotnet cake
