resources:
  containers:
    - container: dotnetsdk
      image: microsoft/dotnet:2.1.503-sdk-stretch
    - container: dind
      image: docker:latest

jobs:
  - job: task_build
    pool: AWS Ubuntu
    container: dotnetsdk
    steps:
      - task: DotNetCoreCLI@2
        displayName: Dotnet Build
        inputs:
          command: build
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: Dotnet Test
        inputs:
          command: test
          projects: '**/*Tests.csproj'
  - job: echo_vars
    dependsOn: cake_build
    pool: AWS Ubuntu
    steps:
      - bash: echo $NBGV_CloudBuildNumber
      - bash: echo $(NBGV_CloudBuildNumber)
  - job: docker_build
    dependsOn: cake_build
    pool: AWS Ubuntu
    steps:
      - task: Docker@1
        displayName: Docker Build
        inputs:
          command: build
          imageName: deployment:$(NBGV_CloudBuildNumber)
  - job: cake_build
    pool: AWS Ubuntu
    container: dotnetsdk
    steps:
      - script: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet tool install -g Cake.Tool --version 0.32.0
          dotnet tool install -g nbgv
          dotnet cake --bootstrap
          dotnet cake
          nbgv cloud -a
      - bash: echo $NBGV_CloudBuildNumber
      - bash: echo $(NBGV_CloudBuildNumber)
