resources:
  containers:
    - container: dotnetsdk
      image: microsoft/dotnet:2.1.503-sdk-stretch

jobs:
  - job: task_build
    pool: AWS Ubuntu
    container: dotnetsdk
    steps:
      - task: DotNetCoreCLI@2
        displayName: Dotnet Build
        inputs:
          command: build
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: Dotnet Test
        inputs:
          command: test
          projects: '**/*Tests.csproj'
  - job: docker_build
    dependsOn: task_build
    pool: AWS Ubuntu
    steps:
      - task: Docker@1
        displayName: Docker Build
        inputs:
          command: build
          imageName: deployment:$(Build.BuildId)
  - job: cake_build
    pool: AWS Ubuntu
    container: dotnetsdk
    steps:
      - script: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet tool install -g Cake.Tool --version 0.32.0
          dotnet cake --bootstrap
          dotnet cake
