version: 2
jobs:
  build-and-test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Install "Cake.Tool" .NET Core global tool
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g Cake.Tool --version 0.32.0
      - run:
          name: Test
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --bootstrap
            dotnet cake
  
  package:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - run:
          name: Docker Build
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --target=PackageApi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - package:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
