version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@2.0.3
jobs:
  build_and_test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Install Tools
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g Cake.Tool --version 0.32.0
            dotnet tool install -g nbgv --version 2.3.38
            apt-get update
            apt-get install -y jq
      - run:
          name: Set Version
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            nbgv cloud
      - run:
          name: Test
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --bootstrap
            dotnet cake
      - run:
          name: Get Version
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            VERSION=`nbgv get-version -f json | jq -r .NuGetPackageVersion`
            echo "NuGet Package Version: $VERSION"

workflows:
  build-deploy:
    jobs:
      - build_and_test
      - aws-ecr/build_and_push_image:
          context: lab-us-east-1
          repo: microservice/deployment
          create-repo: true
          requires:
            - build_and_test
          filters:
            branches:
              only: master
