version: 2.1
executors:
    dotnetsdk:
      docker:
        - image: microsoft/dotnet:2.1.503-sdk-stretch
orbs:
  aws-ecr: circleci/aws-ecr@2.0.3
jobs:
  build_and_test:
    executor: dotnetsdk
    steps:
      - checkout
      - run:
          name: Install Tools
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g Cake.Tool --version 0.32.0
      - run:
          name: Test
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --bootstrap
            dotnet cake

  tag_with_version:
    executor: dotnetsdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "60:fe:77:66:4f:0d:c5:e4:39:d6:d1:72:3b:bb:42:fd"
      - checkout
      - run:
          name: Install Tools
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g nbgv --version 2.3.38
      - run:
          name: Set Version
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            nbgv tag
            git push --tags

workflows:
  build-deploy:
    jobs:
      - build_and_test
      # - aws-ecr/build_and_push_image:
      #     context: lab-us-east-1
      #     repo: microservice/deployment
      #     create-repo: true
      #     requires:
      #       - build_and_test
      #     filters:
      #       branches:
      #         only: master
  tag_with_version:
    jobs:
      - tag_with_version:
          filters:
            branches:
              only: master
