version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@2.0.3
jobs:
  build_and_test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Install "Cake.Tool" .NET Core global tool
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g Cake.Tool --version 0.32.0
      - run:
          name: Test
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --bootstrap
            dotnet cake

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
      - aws-ecr/build_and_push_image:
          repo: microservice/deployment
          create-repo: true
          requires:
            - build_and_test
          filters:
            branches:
              only: master
