version: 2.1
executors:
    dotnetsdk:
      docker:
        - image: microsoft/dotnet:2.1.503-sdk-stretch
orbs:
  aws-ecr: circleci/aws-ecr@2.0.3
jobs:
  build_and_test:
    executor: dotnetsdk
    steps:
      - checkout
      - run:
          name: Install Tools
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g Cake.Tool --version 0.32.0
      - run:
          name: Test
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet cake --bootstrap
            dotnet cake

  tag_with_version:
    executor: dotnetsdk
    parameters:
      fingerprint:
        default: SSH_FINGERPRINT_PUSH
        description: SSH Fingerprint of Deploy Key with Push permissions
        type: env_var_name
    steps:
      - run:
          name: Echo fingerprint
          command: |
            echo "<< parameters.fingerprint >>"
      - add_ssh_keys:
          fingerprints:
            - << parameters.fingerprint >>
      - checkout
      - run:
          name: Install Tools
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            dotnet tool install -g nbgv --version 2.3.38
      - run:
          name: Set Version
          command: |
            export PATH="$PATH:$HOME/.dotnet/tools"
            nbgv tag
            git push --follow-tags

workflows:
  build-deploy:
    jobs:
      - build_and_test
      - aws-ecr/build_and_push_image:
          context: lab-us-east-1
          repo: microservice/deployment
          create-repo: true
          requires:
            - build_and_test
          filters:
            branches:
              only: master
  tag_with_version:
    jobs:
      - tag_with_version:
          filters:
            branches:
              only: master
